apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: plato
type: Opaque
data:
  postgres_password: {{ base64 encoded database password for Plato's database }}
  db_creds_enc_key: {{ base64 encoded random hex-encoded string to encrypt database credentials }}
  license_key: {{ base64 encoded license key given to you by Plato's representative }}
