apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: plato
type: Opaque
data:
  postgres_password: "YWRtaW4K"
  db_creds_enc_key: "NTFhNzBmZWRmMWVhNjA3NzFlMGZkZWNhZmMwZmZlZTE3YzBkZWRmYWNlYjAwY2FjZWQ5MDA5MWVmMWVkMmJlZAo="
  license_key: "ZXlKaGJHY2lPaUpGWkVSVFFTS…UGc3SGgzdlI2OU8p1bXR1LXE1U0prcEM4UFRNTzVaa2duR0FnCg=="
